FROM bjornno/ruby

RUN apt-get update

ADD serf/serf /usr/bin/

ADD . /
RUN bundle install
ENV port 3000
EXPOSE 3000

# start serf
ADD serf/start-serf.sh /start-serf.sh
ADD serf/serf-join.sh /serf-join.sh
ADD serf/supervisord-serf.conf /etc/supervisor/conf.d/supervisord-serf.conf
ADD serf/run.sh /run.sh

RUN chmod 755 /*.sh

CMD ["/run.sh"]

